### ISSUE TITLE
Issue van Gijs

### ISSUE THREAD

**Issue by ghost** [maarten-pennings/flasher#1]
Krijg je een mailtje?

**Comment by maarten-pennings** [comment]
Ja, ik kreeg een mailtje.
Heb ook gevonden (beetje omslachtig) hoe ik een lijst van open issues kan vinden.
 - klik 'Issues' in de zwarte balk
 - in zoek balk vul in 'user:maarten-pennings is:open'
 - de lijst komt eronder.

Ik sluit deze 'issue'; hoop dat dat ok is voor jou :-)
